### ISSUE TITLE
uploader

### ISSUE THREAD

**Issue by Sparh4wk** [tomaskrizek/webshare-downloader#3]
Zdravim,

downloader je super.. chtel jse se jen zeptat, zdali by jste neuvazoval i o uploaderu.

Dekuji

**Comment by nicki-krizek** [comment]
Dobry den,

pro uploader nemam vyuziti, ale nebranil bych se jeho zacleneni do projektu. Kdyz otevrete pull request s funkcnim kodem, kouknu na to a muzu to mergnout. Alternativne se muzeme dohodnout, ze bych to napsal vymenout za nejaky VIP webshare poukaz.

**Comment by Sparh4wk** [comment]
Dobry den,

Omlouvam se za pozdni odpoved, uplne jsem na to zapomnel. Programovat neumim, proto jsem se ptal, jestli jste o uploaderu neuvazoval.  Co se tyce voucheru, nemusel by to byt problem.

Je mozne Vas nejak kontaktovat mimo github?

Dekuji

**Comment by nicki-krizek** [comment]
@Sparh4wk `tomas.krizek (at) mailbox.org` - napiste mi kdyztak nejaky popis toho, co byste od toho ocekaval, jak byste to chtel pouzivat apod.

**Comment by nicki-krizek** [comment]
Zvazoval jsem pripadnou implementaci, ale upload mi do tohoto toolu koncepcne prilis nesedi. Primarne je to ted o praci s API a ziskavani linku, ktere se stahuji externim toolem. Upload by vyzadoval implementaci pro odesilani souboru, ktera by asi nebyla prilis spolehliva a nebo by byla zbytecne slozita.
